### ISSUE TITLE
NullPointException

### ISSUE THREAD

**Issue by tleavitt25526** [tleavitt25526/maze-generation#4]
Creating Maze instance in main method leads to NullPointException error. Code in Maze constructor after instance variable initialization causes it.

**Comment by ranaajeetsingh** [comment]
Cell is class, in Maze constructor; we are creating the 2D array of Cell but we're not filling the array with Cell objects.

code: test.getCell(0, 0) suppose to return the Cell object at 0,0 position which is null that's why operation on it's output throwing NullPointerException.

**Comment by tleavitt25526** [comment]
Thanks!
